### ISSUE TITLE
Grammatical errors 

### ISSUE THREAD

**Issue by melcoleman** [CS-451-Spring-2015/CCSC_Submission_System#18]
Proof read and double check for grammatical and spelling errors throughout the entire website!

**Comment by amandajcoffelt** [comment]
I know I saw one when you register .

**Comment by Nyankuru** [comment]
I think the error you are referring to was on the reviewer register page. In "Review Current Event," event is singular but for the future events it was plural. I changed and made it plural. Please be more specific next time you note grammatical errors. Copy down the link the error is on and the section.

Issue resolved. Closing case.
