### ISSUE TITLE
CCSC DEVEL website down 

### ISSUE THREAD

**Issue by gmims** [CS-451-Spring-2015/CCSC_Submission_System#19]
The loki.lincolnu.edu/~ccscdevel website is down. I tried getting on it from google chrome, firefox, safari, and internet explorer.

**Comment by amandajcoffelt** [comment]
Was there a power outage again? We should probably fix this(high) priority because this will not be good till the next day.

**Comment by melcoleman** [comment]
No there hasn't been a power outage today!

**Comment by Nyankuru** [comment]
The website is back up. Closing case
