### ISSUE TITLE
Not submitting contributions

### ISSUE THREAD

**Issue by Nyankuru** [CS-451-Spring-2015/CCSC_Submission_System#23]
Even if all the required criteria is met for submission, the new site does not let you submit your work. It gives an error every time saying that something went wrong. See attachment!
![submission](https://cloud.githubusercontent.com/assets/5976628/7348739/a64f9b5a-ecb9-11e4-8b20-c397df823c21.PNG)

Page: http://loki.lincolnu.edu/~ccscdevel/NewSubmission.php

**Comment by melcoleman** [comment]
I got this same message and I purposely submitted it twice!

**Comment by gmims** [comment]
Yeah I just got this message which is an error too!

**Comment by Nyankuru** [comment]
Issue was resolved in class. Closing case
