### ISSUE TITLE
Reviewer Registration Background color

### ISSUE THREAD

**Issue by melcoleman** [CS-451-Spring-2015/CCSC_Submission_System#27]
![image](https://cloud.githubusercontent.com/assets/11430189/7353866/6fec5f8a-ecdc-11e4-9598-5702c631a850.png)

**Comment by melcoleman** [comment]
Is the reviewer background on the registration page suppose to be different? I think they should all be the same color!

**Comment by gmims** [comment]
They just changed the color of the background on the reviewer side and it's the same color as the contributor side and the rest of the website. Good job team!

**Comment by Nyankuru** [comment]
Issue resolved. Closing Case
