### ISSUE TITLE
Pane Chair Home Upper and Lower Case Buttons

### ISSUE THREAD

**Issue by amandajcoffelt** [CS-451-Spring-2015/CCSC_Submission_System#31]
On the home page the buttons are both upper and lower case, just like the Nifty Chair.

**Comment by Nyankuru** [comment]
Which home page? Are you talking about the main home page? I can't find the buttons you are referring to

**Comment by Nyankuru** [comment]
That depends on how the contributor chooses to enter in their title.

Non issue. Closing case
