### ISSUE TITLE
Tutorial Chair Home Upper and Lower Case

### ISSUE THREAD

**Issue by amandajcoffelt** [CS-451-Spring-2015/CCSC_Submission_System#32]
The buttons on Tutorial Chair Home is upper and lower case, as well the buttons being too short to read the papers name.

**Comment by Nyankuru** [comment]
I believe that the names in those buttons is what the user puts in as a title when they are making a contribution. If they decide to put it in all upper case or or mix them, it shows up exactly as they typed it in. I don't know if you are suggesting us to change it. What do you think?

Also, we are working on the issue with the buttons being too short.

**Comment by Nyankuru** [comment]
The issue with the buttons being too short has been resolved. The mixture of the upper and lowercase letters depends on what the users put in as the title. There is no need to change it.

Issue resolved. Closing case
