### ISSUE TITLE
Grammar error or suggestion on the home page under Reviewer 

### ISSUE THREAD

**Issue by gmims** [CS-451-Spring-2015/CCSC_Submission_System#34]
It says, "If you are a new Reviewer, you will need to register before you can login below." I feel the word New should also be capitalized.

**Comment by Nyankuru** [comment]
I'm not sure if it should be. I think the R on Reviewer should be lower case instead. What do you think?  @CS-451-Spring-2015/cs451_spring2015

**Comment by Nyankuru** [comment]
Issue resolved. Closing Case
